apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x7u721s56-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x7u721s56-dotnet-basic-gitops